### PR TITLE
Fix tag-to-digest config in installation script

### LINKED ISSUE #35: Installer does not properly skip tag-to-digest for internal OpenShift registries
In `install.sh` [1], a command is issued with the purpose of setting two additional repositories in the list to skip upfront tag-to-digest resolution. However, the outcome of this is not desirable for a couple reasons:

- the list of additional repositories gets appended outside the double quotes around the existing list
- the config map line modified by the command is not indented properly so that it becomes an active configuration

The config map modification looks to be acting on the default Knative `config-controller` config map [2]. Even in the unmodified config map, the example `registriesSkippingTagResolving` configuration is inactive -- essentially commented out in an interesting way.

This issue is making the assumption that the installer is intended to add `docker-registry.default.svc:5000` and `image-registry.openshift-image-registry.svc:5000` to the list of registries to skip as an active configuration. If that assumption is true, the installer does not quite set the configuration appropriately.

[1] https://github.com/openshift-cloud-functions/knative-operators/blob/master/etc/scripts/install.sh#L44-47
[2] https://github.com/knative/serving/blob/master/config/config-controller.yaml

### PR DESCRIPTION
**Pull request by aliok**
Fixes https://github.com/openshift-cloud-functions/knative-operators/issues/35

The configmap `config-controller` of `knative-serving` namespace now has a different structure after the change done [here](https://github.com/knative/serving/commit/7401bce6ea5ca2d0ab43d25720bc52b5b9f9bbb8#diff-aeaefb1b63b460c864c182af57d1650cL35).

Previously, there was a `registriesSkippingTagResolving` entry in the configMap data but now that is removed. There's a `registriesSkippingTagResolving` occurrence in the `_example` key of the configMap data and currently that was what is modified with `sed`.

Current default config map: https://github.com/knative/serving/blob/v0.5.2/config/config-controller.yaml

Output before: https://gist.github.com/aliok/3a81066f05519b948e1edc894f6b7688
Output now: https://gist.github.com/aliok/7ceb5552a34d17855523b301fe6d9ec9

Notes:
* Change is backwards compatible. It overwrites the existing value of `data.registriesSkippingTagResolving`, which was available before https://github.com/knative/serving/commit/7401bce6ea5ca2d0ab43d25720bc52b5b9f9bbb8#diff-aeaefb1b63b460c864c182af57d1650cL35
~~* This PR depends on availability of `yq`. I think it is kind of hard to do this change with `sed`.~~
UPDATE: using `kubectl patch --type merge` now.

### CODE REVIEW

File: etc/scripts/install.sh [hunk 1]
```diff
@@ -44,7 +44,7 @@ enable_interaction_with_registry
 # skip tag resolving for internal registry
 # OpenShift 3 and 4 place the registry in different locations, hence
 # the two hostnames here
-$CMD -n knative-serving get cm config-controller -oyaml | sed "s/\(^ *registriesSkippingTagResolving.*$\)/\1,docker-registry.default.svc:5000,image-registry.openshift-image-registry.svc:5000/" | oc apply -f -
+$CMD -n knative-serving get cm config-controller -oyaml | yq w - "data.registriesSkippingTagResolving" "ko.local,dev.local,docker-registry.default.svc:5000,image-registry.openshift-image-registry.svc:5000" | $CMD apply -f -
```
Comment (jcrossley3) [inline etc/scripts/install.sh]: I don't love the assumption of `yq` here, because as long as we're citing this repo as the way to install the dev preview, we'll need to update docs. I'd prefer a `sed` solution, if possible.

**Review by jcrossley3 — CHANGES_REQUESTED** [review]
Thanks for this -- I totally forgot about upstream moving to the `example` block.

File: etc/scripts/install.sh (hunk 1 above)
Comment (aliok) [reply etc/scripts/install.sh]: sure, let me give it a try with `sed`

Comment (jcrossley3) [reply etc/scripts/install.sh]: Thanks! And fwiw, though I love that you made it backwards-compatible, I'm not sure it needs to be, since master tracks the latest upstream, so if that makes using `sed` simpler...

**Comment by aliok** [comment]
@jcrossley3 changed the script to use `kubectl patch --type merge` and there's no dependency to `yq` anymore.
I had trouble time :cold_sweat:  with `sed` before I realized I can just use `kubectl patch` :smile:

**Review by jcrossley3 — APPROVED** [review]

**Comment by bbrowning** [comment]
We shouldn't be disabling tag-to-digest resolution for the internal registry at all, right? I think it's actually a bug that we still do it. Digest resolution should work out of the box.

**Comment by jcrossley3** [comment]
> We shouldn't be disabling tag-to-digest resolution for the internal registry at all, right? I think it's actually a bug that we still do it. Digest resolution should work out of the box.

I'm not sure why we ever did. :)
